/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006e28",
        "on-primary": "#ffffff",
        "primary-container": "#45fd73",
        "on-primary-container": "#007129",
        secondary: "#006686",
        "secondary-container": "#00c4fe",
        "on-secondary-container": "#004d66",
        tertiary: "#705d00",
        "tertiary-container": "#ffdb47",
        "on-tertiary-container": "#736000",
        background: "#f9f9f9",
        surface: "#f9f9f9",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1b1b1b",
        "on-surface-variant": "#3b4b3a",
        outline: "#6b7c68",
        "outline-variant": "#b9ccb5",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        none: '0px',
        sm: '0px',
        DEFAULT: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"Space Grotesk"', 'sans-serif'],
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Space Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'neu': '4px 4px 0px 0px #000000',
        'neu-heavy': '8px 8px 0px 0px #000000',
        'neu-sm': '2px 2px 0px 0px #000000',
      },
    },
  },
  plugins: [],
}

